### PR TITLE
Allow to overwrite build-flags when generating the doc

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
This enables to build the documentation in https://github.com/mirage/ocaml-github/pull/176

**Comment by dbuenzli** [comment]
Could explain to me how you have the feeling that this https://github.com/mirage/ocaml-github/pull/176/commits/65c1a17f24938a0544b7d72da60a50b1706a8a67 solves your problem ?

**Comment by samoht** [comment]
It allows me to generate and read the docs locally. But yes, it won't probably help for the full release process.

**Comment by dbuenzli** [comment]
See discussion in https://github.com/dbuenzli/topkg/issues/80

**Pull request closed without merging**
